# Generated by Django 2.0.1 on 2018-01-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmechapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='song',
            new_name='Sng',
        ),
    ]
