# Generated by Django 2.2.dev20180628151426 on 2018-10-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmechapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs', models.ManyToManyField(related_name='lists', to='tmechapi.Song')),
            ],
        ),
    ]
