# Generated by Django 2.2.dev20180628151426 on 2018-10-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmechapi', '0002_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='songs',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
