# Generated by Django 2.0.1 on 2018-01-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmechapi', '0002_auto_20180112_2345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sng',
            new_name='Song',
        ),
    ]
