# Generated by Django 2.0.1 on 2018-01-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmechapi', '0003_auto_20180112_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('songs', models.ManyToManyField(related_name='listeners', to='tmechapi.Song')),
            ],
            options={
                'ordering': ('username',),
            },
        ),
    ]
